# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store

  desc "Lane for distributing app using Firebase App Distributions"
  lane :distribute do
      gradle(task: "clean assembleRelease")
      firebase_app_distribution(
          service_credentials_file: "D:\Project Files\My Application\serviceaccount.json",
          app: "1:412390502424:android:8a5567a22b363393a6936d",
          release_notes_file: "D:\Project Files\My Application\releasenotes.txt",
          # groups_file: "FirebaseAppDistributionConfig/groups.txt",
	  testers: "dnyaneshwar1926@gmail.com, dnyaneshwar@iwizardsolutions.com"
          firebase_cli_token: "1//0gXLTibjs9h31CgYIARAAGBASNwF-L9IrKKYHiklqsBTxt8rl9_q0D4OW4XqNJjuiaGzqX1Eby_IZvBqrIkdNoRhx-Ak6rqLDFFk"
      )
  end
end
